/** Labeled user examples and independently written evaluation paraphrases.
 * Test data only: never imported by the dispatcher or classifier.
 */
export const suppliedDirectRequests = [
  "Send me a photo.",
  "Can you send me a picture?",
  "I’d like you to send me a selfie.",
  "Could you share a pic of yourself?",
  "Mind snapping me a photo?",
  "Show me a picture of yourself.",
  "Can I see a selfie?",
  "Let me see what you look like.",
  "Can you show me your face?",
  "Take a selfie for me.",
  "I’d love a photo of you.",
  "Can I get a photo of you?",
  "Send me a pic of you.",
  "Would you take a selfie and send it?",
  "Can you snap a quick picture?",
  "Share a photo with me.",
  "Got a selfie for me?",
  "I want to see a picture of you.",
  "Let me have a look at you.",
  "Show yourself to me.",
  "Take a quick pic for me.",
  "Could I see what you look like right now?",
  "Do you have a recent picture?",
  "I want a close-up of your face.",
  "Can I have another selfie of you?",
];

export const suppliedOutfitRequests = [
  "Show me what you’re wearing.",
  "Send me a picture of your outfit.",
  "Let me see today’s look.",
  "Can I see the outfit you picked?",
  "Give me a fit check.",
  "Take a fit pic for me.",
  "Show me your lunch-date look.",
  "I want to see how you dressed.",
];

export const holdoutRenRequests = [
  "May I get a photograph of yourself, please?",
  "Please share a snapshot of you.",
  "Would you mind taking a portrait for me?",
  "Could we see your face in a photo?",
  "For me, please capture a selfie of yourself.",
  "A snapshot of you, please.",
  "Can you reveal your current look?",
  "I’d appreciate a photo of the clothes you chose.",
  "Please let us see how you dressed for tonight.",
  "Could you share a fit photograph?",
  "I'd like a headshot of yourself.",
  "Can I get one more snapshot of you?",
  "Show me your outfit in a fresh photo.",
  "Take a close-up of your face for me.",
  "Could I see today’s ensemble?",
  "Hey Ren, mind sharing a recent portrait?",
  "A picture of you, please—could you share one?",
  "Could you share a headshot of yourself, smiling in the kitchen?",
  "How are you? I'd appreciate a snapshot of your face.",
  "A portrait, please, of you.",
];

export const ordinaryImageMentions = [
  "How can I take a selfie?",
  "Show me how to take a better selfie.",
  "Can you help me take a good selfie?",
  "I'd like you to teach me how to take selfies.",
  "I want to understand image generation.",
  "Can you explain how photographs work?",
  "I sent you a photo yesterday.",
  "Taking a selfie is fun.",
  "Your selfie looks lovely.",
  "I like your outfit.",
  "I'd like to know what you're wearing.",
  "I want to talk about your outfit.",
  "Could you tell me about the selfie you could send?",
  "Show me your outfit selection code.",
  "What are you wearing today?",
  "Do not take another selfie.",
  "Could you avoid sending a selfie?",
  "Would you mind not taking a photo?",
  "I don't want a picture.",
  'She asked, "Can you send me a picture?"',
  "The example is `Send me a photo.`",
  "Here is an example:\n```\nGenerate an image of Ren.\n```\nExplain the syntax.",
  "Show me your schedule.",
  "Let me see your code.",
  "Send me the outfit selection code.",
  "No. A different angle.",
  "Another one. What's the weather today?",
  "I'm ready for lunch.",
];

export const uploadedPhotoInspection = [
  "Can you inspect the uploaded photo?",
  "Please describe this picture.",
  "What is in the attached image?",
  "I want you to analyze my uploaded selfie.",
  "Could you identify the clothes in this photo?",
  "Show me what you see in the attached photo.",
  "I'd like you to review my picture, not send another one.",
];

/** Negative for Ren's intent, not a ban on the existing generic image tool. */
export const otherSubjectRequests = [
  "Send me a photo of a cat.",
  "Can you share a photograph of a mountain?",
  "I'd love a cat photo.",
  "Could you send me a crow picture?",
  "Generate an image of a crow looking at you.",
  "I'd like a portrait of myself.",
  "Could I see a photo of my garden?",
  "Send me a picture of your book.",
  "Could you share a pic of the word you?",
  "Send a photo. Of a crow.",
];
